favicon: null
name: AZCB
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 1
  lightness: 0.8276047
  brandColors:
    - '#0E0504'
    - '#646D6E'
    - '#D89980'
    - '#D7E0E0'
    - '#D01F2F'
  rhythmicContrast: 0.3236699
typography_spectrum: 0.8286788
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
